{{- include "bright.validateMasterKeyConfig" . -}}
{{- if and .Values.config.masterKey (not .Values.config.masterKeySecret.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bright.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bright.labels" . | nindent 4 }}
type: Opaque
stringData:
  master-key: {{ .Values.config.masterKey | quote }}
{{- end }}
