apiVersion: v1
kind: Service
metadata:
  name: {{ include "bright.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bright.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
    name: {{ .Values.service.portName }}
  {{- if gt (int .Values.replicaCount) 1 }}
  - port: {{ .Values.raft.port }}
    targetPort: raft
    protocol: TCP
    name: raft
  {{- end }}
  selector:
    {{- include "bright.selectorLabels" . | nindent 4 }}
