{{- if gt (int .Values.replicaCount) 1 }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bright.fullname" . }}-headless
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bright.labels" . | nindent 4 }}
    app.kubernetes.io/component: headless
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    {{- include "bright.selectorLabels" . | nindent 4 }}
  ports:
  - name: raft
    port: {{ .Values.raft.port }}
    targetPort: raft
    protocol: TCP
{{- end }}
