apiVersion: v2
name: bright
description: A Helm chart for Bright - High-performance full-text search database
type: application
version: 0.2.0
appVersion: "1.0.0"
keywords:
  - search
  - full-text
  - database
  - bleve
home: https://github.com/nnstd/bright
maintainers:
  - name: Nikita Ganzikov
    email: nganzikov@gmail.com
